# Generated by Django 4.0.4 on 2022-05-12 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dsNameCharge', models.CharField(help_text='Ingrese nombre del cargo máximo 45 caracteres', max_length=45, verbose_name='Nombre Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Enterprises',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dsNameEnterprise', models.CharField(help_text='Ingrese nombre de la empresa máximo 45 caracteres', max_length=45, verbose_name='Nombre Empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Priorities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dsNamePriority', models.CharField(help_text='Ingrese nombre de la prioridad máximo 10 caracteres', max_length=10, verbose_name='Prioridad')),
            ],
            options={
                'verbose_name': 'Prioridad',
                'verbose_name_plural': 'Prioridades',
            },
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dsNameStatus', models.CharField(help_text='Ingrese nombre del estado máximo 24 caracteres', max_length=24, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dsNameProject', models.CharField(help_text='Ingrese nombre del proyecto máximo 45 caracteres', max_length=45, verbose_name='Nombre Proyecto')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dueño Proyecto')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogHoursApp.priorities', verbose_name='Prioridad')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LogHoursApp.statuses', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='LogHours',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dsActivity', models.CharField(help_text='Actividad realizada máximo 200 caracteres', max_length=200, verbose_name='Actividad')),
                ('nmBusinessHour', models.DecimalField(decimal_places=2, help_text='Ingrese hora laboral maximo 8 caracteres', max_digits=8, verbose_name='Hora laboral')),
                ('nmNoBusinessHour', models.DecimalField(decimal_places=2, help_text='Ingrese hora no laboral maximo 8 caracteres', max_digits=8, verbose_name='Hora no laboral')),
                ('date', models.DateTimeField(auto_now=True, help_text='Ingresa la fecha de registro/actualización', verbose_name='Fecha registro')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogHoursApp.priorities', verbose_name='Prioridad')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogHoursApp.projects', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Resgistro de horas',
                'verbose_name_plural': 'Resgistro de horas',
            },
        ),
        migrations.CreateModel(
            name='EnterprisesUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogHoursApp.enterprises', verbose_name='Empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Empresa por usuario',
                'verbose_name_plural': 'Empresas por usuarios',
            },
        ),
        migrations.CreateModel(
            name='ChargesUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogHoursApp.charges', verbose_name='Cargo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cargo por usuario',
                'verbose_name_plural': 'Cargos por usuarios',
            },
        ),
    ]
