# Generated by Django 4.0.4 on 2022-05-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogHoursApp', '0002_alter_projects_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loghours',
            name='date',
            field=models.DateTimeField(blank=True, help_text='Ingresa la fecha de registro/actualización', verbose_name='Fecha registro'),
        ),
    ]
